# Generated by Django 4.2.4 on 2023-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_not_negative'),
        ),
    ]
