# Generated by Django 4.2.4 on 2023-08-19 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('file', models.FileField(upload_to='')),
            ],
            bases=('store.product',),
            managers=[
                ('in_stock', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('in_stock', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('stock_count', models.IntegerField(help_text='How many items are currently in stock.')),
            ],
            bases=('store.product',),
            managers=[
                ('in_stock', django.db.models.manager.Manager()),
            ],
        ),
    ]
